[package]
name = "haskell_ghci_parser"
version = "0.1.0"
authors = ["Sebastián Felgueras <sebastian.felgueras@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
